"""Deterministic Markdown normalizer for the final report's Source Notes table.

The ``## Source Notes`` section is required (by ``FINAL_PROMPT``) to be a
Markdown table, but LLM output drifts: rows come back bullet-prefixed
(``- doc_001 | …``), the header/separator goes missing, or the Doc ID cell is
written as a bare ``doc_1`` instead of the canonical ``[doc_001]``. Any of these
breaks table rendering in the document summary view.

:func:`normalize_final_report_markdown` repairs **only** the Source Notes
section — the rest of the report (prose, math, other tables) is returned
unchanged. It is pure and idempotent (re-running on canonical output is a
no-op) and makes no LLM call.
"""

from __future__ import annotations

import re


_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*$")
_SOURCE_NOTES_RE = re.compile(r"^source\s+notes$", re.IGNORECASE)
_BULLET_RE = re.compile(r"^[-*+]\s+")
_SEPARATOR_CELL_RE = re.compile(r"^:?-{3,}:?$")
_DOC_ID_RE = re.compile(r"\[?doc[_-]?(\d+)\]?", re.IGNORECASE)
_PIPE_SPLIT_RE = re.compile(r"(?<!\\)\|")

_HEADER = "| Doc ID | Title / Type | Year | What it contributes | Reliability / Caveat |"
_SEPARATOR = "|---|---|---|---|---|"


def normalize_final_report_markdown(md: str) -> str:
    """Return *md* with its ``## Source Notes`` table normalized in place."""
    if not md or "|" not in md:
        return md or ""
    lines = md.split("\n")
    start = _find_source_notes_heading(lines)
    if start is None:
        return md
    end = _find_section_end(lines, start)
    section = lines[start + 1 : end]
    fixed = _normalize_section(section)
    if fixed == section:
        return md
    return "\n".join(lines[: start + 1] + fixed + lines[end:])


def _find_source_notes_heading(lines: list[str]) -> int | None:
    for i, line in enumerate(lines):
        match = _HEADING_RE.match(line)
        if match and _SOURCE_NOTES_RE.match(match.group(1).strip()):
            return i
    return None


def _find_section_end(lines: list[str], start: int) -> int:
    for i in range(start + 1, len(lines)):
        if _HEADING_RE.match(lines[i]):
            return i
    return len(lines)


def _normalize_section(section: list[str]) -> list[str]:
    row_indices = [i for i, line in enumerate(section) if "|" in line]
    if not row_indices:
        # No table at all (e.g. the section is just "- None") — leave as-is.
        return section
    first, last = row_indices[0], row_indices[-1]
    pre = section[:first]
    post = section[last + 1 :]
    data_rows: list[str] = []
    for line in section[first : last + 1]:
        row = _normalize_row(line)
        if row is not None:
            data_rows.append(row)
    table = [_HEADER, _SEPARATOR] + data_rows
    return pre + table + post


def _normalize_row(line: str) -> str | None:
    """Normalize one row to ``| … |``; return ``None`` for header/separator rows.

    Header and separator rows are dropped here because the caller regenerates a
    single canonical header + separator pair.
    """
    text = _BULLET_RE.sub("", line.strip())
    if not text or "|" not in text:
        return None
    if text.startswith("|"):
        text = text[1:]
    if text.endswith("|"):
        text = text[:-1]
    cells = [_normalize_cell(c) for c in _PIPE_SPLIT_RE.split(text)]
    while cells and cells[-1] == "":
        cells.pop()
    if not cells:
        return None
    # Separator row (``---|---|…``) → regenerated by the caller.
    if all(_SEPARATOR_CELL_RE.match(c.replace(" ", "")) for c in cells if c):
        return None
    # Canonical header row → regenerated by the caller.
    joined = " ".join(cells).lower()
    if "doc id" in joined and "contribut" in joined:
        return None
    cells[0] = _canonical_doc_cell(cells[0])
    return "| " + " | ".join(cells) + " |"


def _normalize_cell(cell: str) -> str:
    cell = (
        cell.replace("<br>", "; ")
        .replace("<br/>", "; ")
        .replace("<br />", "; ")
    )
    cell = _BULLET_RE.sub("", cell.strip())
    return re.sub(r"\s+", " ", cell).strip()


def _canonical_doc_cell(cell: str) -> str:
    """``doc_1`` / ``doc-1`` / ``[doc_1]`` → ``[doc_001]``; non-id cells kept."""
    match = _DOC_ID_RE.search(cell)
    if not match:
        return cell
    return f"[doc_{int(match.group(1)):03d}]"


__all__ = ["normalize_final_report_markdown"]
